// Local built-PWA regression; API is synthetic and all other origins are blocked.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),build=path.resolve(root,process.argv[2]||'.tmp/local-build-2.1.18-20261002-final');
const {chromium}=require(path.join(root,'.tmp/billing-qa/node_modules/playwright'));
const AxeBuilder=require(path.join(root,'.tmp/billing-qa/node_modules/@axe-core/playwright')).default;
assert(build.startsWith(path.join(root,'.tmp')+path.sep));
const zoom=process.env.ATYLLA_QA_ZOOM==='2';
const forcedTheme=process.env.ATYLLA_QA_THEME||'';const out=path.join(root,'.tmp/changes-20261002/requested-browser'+(forcedTheme?'-'+forcedTheme:'')+(zoom?'-zoom':''));fs.mkdirSync(out,{recursive:true});
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));
const date=[monday.getFullYear(),String(monday.getMonth()+1).padStart(2,'0'),String(monday.getDate()).padStart(2,'0')].join('-');
const server=http.createServer((req,res)=>{let file=path.resolve(build,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!file.startsWith(build+path.sep)&&file!==build){res.writeHead(403);return res.end();}if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(build,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.ttf':'font/ttf','.png':'image/png'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
const results=[];let browser,debugPage,debugCalls;
const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({build,scope:'Synthetic offline API, local Chrome. No production/backend verification.',zoomEquivalent:zoom,results},null,2));
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-background-networking','--disable-component-update','--no-first-run']});
 for(const width of (process.env.ATYLLA_QA_WIDTH?[+process.env.ATYLLA_QA_WIDTH]:zoom?[720]:[390,320,768,1024,1366,1440])){
  const context=await browser.newContext({viewport:{width,height:zoom?500:width===1366||width===1024?768:width===390?844:width===320?800:1000},deviceScaleFactor:zoom?2:1,serviceWorkers:'block',reducedMotion:width===320?'reduce':'no-preference'});
  const page=await context.newPage();debugPage=page;page.setDefaultTimeout(9000);
  const calls=[],errors=[],blocked=[],dialogs=[];debugCalls=calls;page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{dialogs.push(d.type());await d.dismiss();});
  const clients=['Adam QA','Beata QA','Celina QA'].map((name,i)=>({id:id(i+1),name,billing_type:'package',package_size:10,package_current_count:2,active_package_id:i===2?id(13):null,package_purchase_date:i===2?date:null,shared_with:[],training_schedule:[],strength_progression:[],payment_history:[],updated_at:'2026-01-01T00:00:00Z'}));
  const events=clients.map((c,i)=>({id:id(i+20),client_id:c.id,clients:c,event_date:date,event_hour:9+i,status:'active',is_settled:false}));
  let pkgs=[{id:id(13),client_id:id(3),size:10,offset:0,start_training_id:id(22),end_training_id:null,created_at:'2026-01-01T00:00:00Z'},{id:id(14),client_id:id(3),size:5,offset:0,start_training_id:id(22),end_training_id:id(22),created_at:'2025-01-01T00:00:00Z'}];
  let failStart=false,delayStart=false,failDelete=false,failEdit=false;
  await context.addInitScript(theme=>{localStorage.setItem('atylla_session_v2',JSON.stringify({access_token:'synthetic-offline',refresh_token:'synthetic-refresh',idle_token:'synthetic-lease',idle_expires_at:Math.floor(Date.now()/1000)+259200,session_id:'synthetic-session',email:'nobody@example.invalid',revision:0}));if(theme)localStorage.setItem('appThemeMode',theme);else if(innerWidth===320)localStorage.setItem('appThemeMode','light');},forcedTheme);
  await context.route('**/*',async route=>{
   const req=route.request(),u=new URL(req.url());if(u.origin===origin)return route.continue();if(u.origin!=='http://127.0.0.1:8000'){blocked.push(u.origin);return route.abort();}
   const payload=req.postData()?req.postDataJSON():null;calls.push({path:u.pathname,method:req.method(),payload});let body=[],status=200;await new Promise(r=>setTimeout(r,50));
   if(u.pathname==='/auth/activity')body={idle_token:'synthetic-lease',idle_expires_at:Math.floor(Date.now()/1000)+259200,session_id:'synthetic-session'};
   else if(u.pathname==='/clients/')body=clients;
   else if(u.pathname.startsWith('/calendar/week/'))body=events;
   else if(u.pathname.startsWith('/calendar/week-summary/'))body={events:[],absences:[],session_rows:['done','paid','planned','free','cancel','unknown','removed'].map((state,i)=>({id:id(90+i),date,hour:9+i,state,name:'ROW-'+state,detail:''}))};
   else if(u.pathname==='/calendar/'&&req.method()==='GET')body=events.filter(e=>e.client_id===u.searchParams.get('client_id'));
   else if(u.pathname==='/calendar/'&&req.method()==='POST'){if(failEdit){status=503;body={detail:'Syntetyczny błąd edycji'};}else{clients[2].package_current_count++;body={...payload,id:id(99)};}}
   else if(u.pathname==='/calendar/absences'&&req.method()==='POST'){body={...payload,id:id(40)};const e=events.find(e=>e.client_id===payload.client_id);e.status='cancelled';e.is_settled=payload.paid;}
   else if(/^\/clients\/[^/]+\/packages$/.test(u.pathname)){if(req.method()==='POST'){if(delayStart)await new Promise(r=>setTimeout(r,1200));if(failStart){status=503;body={detail:'Syntetyczny błąd pakietu'};}else{const c=clients.find(c=>c.id===u.pathname.split('/')[2]);c.active_package_id=id(60);c.package_purchase_date=date;c.shared_with=payload.shared_client_ids;body={id:id(60),...payload};}}else body=pkgs;}
   else if(u.pathname.startsWith('/clients/packages/')&&req.method()==='DELETE'){if(failDelete){status=503;body={detail:'Syntetyczny błąd usunięcia'};}else{pkgs=pkgs.filter(p=>p.id!==u.pathname.split('/').at(-1));body={ok:true};}}
   else if(u.pathname.startsWith('/clients/'))body=clients.find(c=>c.id===u.pathname.split('/')[2])||{};
   else if(u.pathname.includes('/exercises/by-group'))body={};
   else if(u.pathname==='/trainer/overview')body={totals:{done:3,paid:2,planned:4,free:90,unknown:0,clients_done:1,clients_planned:1,cancellation_rate:40},previous_done:1,previous_label:'poprzedni miesiąc',months:Array.from({length:12},(_,i)=>({month:i+1,total:99,done:3,paid:2,planned:4,free:90})),weeks:[],rows:[],updated_at:new Date().toISOString()};
   await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body),headers:{'Access-Control-Allow-Origin':'*'}});
  });
  const slot=h=>page.locator(`[data-slot-date="${date}"][data-slot-hour="${h}"]:visible`),drawer=page.getByTestId('calendar-drawer');
  const startCalls=()=>calls.filter(c=>c.path===`/clients/${id(1)}/packages`&&c.method==='POST');
  async function boot(){await page.goto(origin);await slot(9).getByText(/Adam QA/).waitFor();await page.waitForTimeout(300);}
  async function openScreen(label){await boot();await page.mouse.click(32,105);await page.getByText('Wyloguj',{exact:true}).waitFor();await page.getByText(label,{exact:true}).click();await page.waitForTimeout(450);}
  async function capture(name){await page.waitForTimeout(350);await page.screenshot({path:path.join(out,`${width}-${name}.png`)});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);const violations=(await new AxeBuilder({page}).analyze()).violations.filter(v=>['serious','critical'].includes(v.impact)).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.html)}));results.push({width,name,overflow,violations});save();assert(!overflow,name+' overflow');}
  async function dismiss(){await page.getByRole('dialog').getByRole('button',{name:'OK',exact:true}).click();await page.waitForTimeout(350);}
  await boot();await slot(9).click();await page.getByTestId('drawer-start-package').waitFor();
  const boxes=await drawer.locator('[tabindex="0"]').evaluateAll(els=>els.map(e=>({text:e.innerText.replace(/\s+/g,' ').trim(),rect:e.getBoundingClientRect().toJSON()})));
  const startBox={text:'Rozpocznij pakiet',rect:await page.getByTestId('drawer-start-package').boundingBox()};assert(boxes.some(b=>b.text!=='Rozpocznij pakiet'&&Math.abs(b.rect.y-startBox.rect.y)<2),'Start package must share a row');
  const textFit=await page.getByTestId('drawer-start-package').evaluate(el=>{const t=el.firstElementChild,r=el.getBoundingClientRect(),tr=t.getBoundingClientRect();return tr.left>=r.left&&tr.right<=r.right+1&&tr.top>=r.top&&tr.bottom<=r.bottom+1&&t.scrollWidth<=t.clientWidth+1;});assert(textFit,'Package label must fit');await capture('compact-drawer');
  await page.getByTestId('drawer-start-package').click();const shared=page.getByRole('checkbox',{name:'Pakiet łączony',exact:true});await shared.press('Space');await page.waitForTimeout(150);assert.equal(await shared.getAttribute('aria-checked'),'true');assert.equal(await shared.evaluate(e=>getComputedStyle(e).outlineStyle),'solid');
  assert.equal(await page.getByRole('checkbox',{name:'Celina QA',exact:true}).count(),0);
  await page.getByRole('button',{name:'Rozpocznij',exact:true}).click();await page.getByRole('dialog',{name:'Wybierz uczestnika'}).waitFor();assert.equal(startCalls().length,0);await dismiss();
  await page.getByRole('checkbox',{name:'Beata QA',exact:true}).press('Enter');assert.equal(await page.getByRole('checkbox',{name:'Beata QA',exact:true}).getAttribute('aria-checked'),'true');await capture('shared-package');
  failStart=true;await page.getByRole('button',{name:'Rozpocznij',exact:true}).click();await page.getByRole('dialog').waitFor();await dismiss();assert(await shared.isVisible());assert.equal(startCalls().length,1);assert.deepEqual(startCalls()[0].payload.shared_client_ids,[id(2)]);
  failStart=false;delayStart=true;const before=startCalls().length;await page.getByRole('button',{name:'Rozpocznij',exact:true}).dblclick();await drawer.waitFor({state:'hidden'});assert.equal(startCalls().length,before+1);assert.equal(clients[0].active_package_id,id(60));
  await slot(10).click();await drawer.getByText('Odwołaj trening',{exact:true}).click();assert(!/nieopłac|bez płatności/i.test(await drawer.innerText()));await capture('paid-cancellation');await drawer.getByText('Potwierdź odwołanie',{exact:true}).click();await drawer.waitFor({state:'hidden'});assert.equal(calls.find(c=>c.path==='/calendar/absences'&&c.method==='POST').payload.paid,true);
  await boot();await page.getByText('PAKIET',{exact:true}).click();await slot(11).click();await page.getByText('Rozliczenia klienta',{exact:true}).waitFor();assert.equal(await page.locator('[data-testid^="payment-card-"]:visible').count(),1);const card=page.getByTestId(`payment-card-${id(3)}`);await card.getByText('Historia',{exact:true}).click();await page.getByText('Historia płatności',{exact:true}).waitFor();
  const history=()=>page.getByText('Historia płatności',{exact:true}).locator('../..');
  const trash=()=>history().getByText(/Pula: 5/).locator('../../..').locator('[tabindex="0"]').last();
  failDelete=true;await trash().click();await page.getByRole('dialog').getByRole('button',{name:'Tak, skasuj',exact:true}).click();await page.getByRole('dialog',{name:'Błąd',exact:true}).waitFor();await dismiss();assert(await history().getByText('Celina QA',{exact:true}).isVisible());assert(await history().getByText(/Pula: 5/).isVisible());
  failDelete=false;await trash().click();await page.getByRole('dialog').getByRole('button',{name:'Tak, skasuj',exact:true}).click();await page.getByRole('dialog',{name:'Sukces',exact:true}).waitFor();await dismiss();await page.getByText('Historia płatności',{exact:true}).waitFor();assert(await history().getByText('Celina QA',{exact:true}).isVisible());assert.equal(await history().getByText(/Pula: 5/).count(),0);await capture('history-after-delete');
  await page.getByText('Historia płatności',{exact:true}).locator('..').locator('[tabindex="0"]').click();
  const edit=()=>card.getByText('2 / 10',{exact:true}).locator('..').locator('[tabindex="0"]').first();await edit().click();await page.getByText('Edytuj Licznik',{exact:true}).waitFor();await page.getByRole('textbox').first().fill('3');failEdit=true;await page.getByText('Zapisz Zmiany',{exact:true}).click();await page.getByRole('dialog',{name:'Błąd',exact:true}).waitFor();await dismiss();assert(await page.getByText('Edytuj Licznik',{exact:true}).isVisible());failEdit=false;await page.getByText('Zapisz Zmiany',{exact:true}).click();await page.getByRole('dialog',{name:'Sukces',exact:true}).waitFor();await dismiss();assert(await card.getByText('3 / 10',{exact:true}).isVisible());
  await openScreen('Strefa Trenera');await page.getByTestId('annual-chart').waitFor();const chart=page.getByTestId('annual-chart');await chart.getByText('Pokaż liczby całego roku',{exact:true}).click();assert.equal(await chart.getByText(/· 5 sesji/).count(),13);assert(!/Zaplanowane|Nieopłacone|bez płatności/i.test(await chart.innerText()));await chart.scrollIntoViewIfNeeded();await capture('annual-paid-and-done');
  await openScreen('Podsumowanie tygodnia');await page.getByText('3 treningów',{exact:true}).waitFor();for(const s of ['done','paid','planned'])assert(await page.getByText('ROW-'+s,{exact:true}).isVisible());for(const s of ['free','cancel','unknown','removed'])assert.equal(await page.getByText('ROW-'+s,{exact:true}).count(),0);await capture('week-filter');
  assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);assert.deepEqual(dialogs,[]);results.push({width,status:results.some(r=>r.width===width&&r.violations?.length)?'FAIL_A11Y':'PASS',functionalStatus:'PASS',checks:['compact same row','label fits','shared keyboard checkbox','eligible members only','invalid empty selection','failed package retained','shared payload','no duplicate start','paid cancellation only','history delete error preserves context','history delete refresh preserves context','edit error retained and success refreshed','annual done plus paid only','week excludes free'],errors,blocked,dialogs,calls});save();console.log(JSON.stringify({width,status:results.at(-1).status}));await context.close();
 }
 assert.equal(results.filter(r=>r.violations?.length).length,0,'Serious/critical axe violations recorded in report.json');
})().catch(async e=>{console.error(e);process.exitCode=1;if(debugPage&&!debugPage.isClosed()){await debugPage.screenshot({path:path.join(out,'failure.png')});fs.writeFileSync(path.join(out,'failure.txt'),await debugPage.locator('body').innerText());console.error((await debugPage.locator('body').innerText()).slice(-2400));console.error(JSON.stringify(debugCalls.slice(-8)));}save();}).finally(async()=>{if(browser)await browser.close();server.close();});
